import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface LeaseListOptions {
  leases: any[]
  filterContext: {
    property: string
    type: 'ACTIVE' | 'EXPIRING'
  }
}

export const generateLeaseListPDF = ({ leases, filterContext }: LeaseListOptions) => {
  const doc = new jsPDF()

  // --- 1. BRANDING & HEADER ---
  doc.setFontSize(22)
  doc.setTextColor(22, 163, 74) 
  doc.setFont("helvetica", "bold")
  doc.text("OneLink PMS", 14, 20)

  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.setFont("helvetica", "normal")
  doc.text("Lease Management Report", 14, 25)

  doc.setFontSize(16)
  doc.setTextColor(0)
  doc.setFont("helvetica", "bold")
  const title = filterContext.type === 'EXPIRING' ? "EXPIRING LEASES" : "ACTIVE LEASES"
  doc.text(title, 195, 20, { align: 'right' })

  // --- 2. METADATA ---
  const boxColor: [number, number, number] = filterContext.type === 'EXPIRING' ? [255, 247, 237] : [240, 253, 244] 
  const borderColor: [number, number, number] = filterContext.type === 'EXPIRING' ? [253, 186, 116] : [187, 247, 208]

  doc.setFillColor(...boxColor)
  doc.setDrawColor(...borderColor)
  doc.roundedRect(14, 32, 182, 20, 2, 2, 'FD')

  doc.setFontSize(9)
  doc.setTextColor(50)
  
  // FIX: Date Generated dd/mm/yyyy
  doc.text(`Generated: ${new Date().toLocaleString('en-GB')}`, 20, 40)
  doc.text(`Total Leases: ${leases.length}`, 20, 46)

  doc.text(`Property Filter: ${filterContext.property}`, 190, 40, { align: 'right' })
  doc.text(`Report Type: ${filterContext.type}`, 190, 46, { align: 'right' })

  // --- 3. DATA PREPARATION ---
  const tableData = leases.map(l => {
    // FIX: Start/End Dates dd/mm/yyyy
    const start = new Date(l.start_date).toLocaleDateString('en-GB')
    const end = l.end_date ? new Date(l.end_date).toLocaleDateString('en-GB') : 'Indefinite'
    
    return [
      l.tenants?.name || 'Unknown',
      l.tenants?.phone || '-',
      l.units?.unit_number || '-',
      l.units?.properties?.name || '-',
      `${start} - ${end}`,
      `${Number(l.rent_amount).toLocaleString()} RWF`
    ]
  })

  // --- 4. TABLE RENDER ---
  const headerColor: [number, number, number] = filterContext.type === 'EXPIRING' ? [194, 65, 12] : [22, 163, 74] 

  autoTable(doc, {
    startY: 60,
    head: [['Tenant', 'Phone', 'Unit', 'Property', 'Duration', 'Rent']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: headerColor,
      textColor: 255,
      fontStyle: 'bold',
      halign: 'left'
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
      textColor: 50,
      lineColor: [229, 231, 235],
      lineWidth: 0.1
    },
    columnStyles: {
      0: { fontStyle: 'bold' }, 
      5: { halign: 'right', fontStyle: 'bold' } 
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    didDrawPage: (data) => {
        const pageHeight = doc.internal.pageSize.height
        const pageWidth = doc.internal.pageSize.width
        
        doc.setDrawColor(200)
        doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15)
        
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text("Generated by OneLink Property Management System", 14, pageHeight - 10)
        
        const pageNum = "Page " + doc.getNumberOfPages()
        doc.text(pageNum, 195, pageHeight - 10, { align: 'right' })
    }
  })

  const fileName = `Lease_Report_${filterContext.type}_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}