import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export const generateReceiptPDF = (invoice: any) => {
  const doc = new jsPDF()

  // --- 1. BRANDING & HEADER ---
  doc.setFontSize(20)
  doc.setFont("helvetica", "bold")
  doc.text("UMUYENZI PLAZA", 14, 22)
  
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(100)
  doc.text("KN 5 Rd, Remera, Kigali", 14, 28)
  doc.text("Phone: +250 788 000 000", 14, 33)

  // --- 2. RECEIPT INFO (Right Side) ---
  doc.setFontSize(24)
  doc.setTextColor(22, 163, 74) // Green-600
  doc.text("RECEIPT", 195, 22, { align: 'right' })
  
  doc.setFontSize(10)
  doc.setTextColor(0)
  doc.text(`Receipt #: REC-${invoice.id.slice(0, 6).toUpperCase()}`, 195, 30, { align: 'right' })
  
  // FIX: Force dd/mm/yyyy
  const paymentDate = invoice.payment_date 
    ? new Date(invoice.payment_date).toLocaleDateString('en-GB')
    : new Date().toLocaleDateString('en-GB')
    
  doc.text(`Date Paid: ${paymentDate}`, 195, 35, { align: 'right' })

  // --- 3. BILL TO ---
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text("Received From:", 14, 50)
  
  doc.setFontSize(12)
  doc.setTextColor(0)
  doc.setFont("helvetica", "bold")
  doc.text(invoice.leases?.tenants?.name || "Valued Tenant", 14, 56)
  
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.text(`Unit: ${invoice.leases?.units?.unit_number || 'N/A'}`, 14, 61)

  // --- 4. WATERMARK ---
  doc.saveGraphicsState()
  doc.setTextColor(220, 252, 231) // Green-100
  doc.setFontSize(60)
  doc.text("PAID", 105, 120, { align: 'center', angle: 45 })
  doc.restoreGraphicsState()

  // --- 5. TABLE ---
  const rentPeriod = new Date(invoice.due_date).toLocaleString('default', { month: 'long', year: 'numeric' })
  
  autoTable(doc, {
    startY: 75,
    head: [['Payment For', 'Period', 'Amount']],
    body: [
      [
        `Rent Payment - Unit ${invoice.leases?.units?.unit_number}`, 
        rentPeriod, 
        `${Number(invoice.amount_paid || invoice.amount).toLocaleString()} RWF`
      ],
    ],
    theme: 'grid',
    headStyles: { 
        fillColor: [22, 163, 74], 
        textColor: 255,
        fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 'auto' },
      2: { halign: 'right', fontStyle: 'bold' }
    },
    styles: {
        minCellHeight: 12,
        valign: 'middle'
    }
  })

  // --- 6. TOTALS ---
  // @ts-ignore
  const finalY = doc.lastAutoTable.finalY + 10

  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text("Total Paid:", 140, finalY)
  
  doc.setFontSize(14)
  doc.setTextColor(22, 163, 74) 
  doc.setFont("helvetica", "bold")
  doc.text(`${Number(invoice.amount_paid || invoice.amount).toLocaleString()} RWF`, 195, finalY, { align: 'right' })

  // --- 7. FOOTER ---
  const pageHeight = doc.internal.pageSize.height
  const pageWidth = doc.internal.pageSize.width
  
  doc.setDrawColor(200)
  doc.line(10, pageHeight - 20, pageWidth - 10, pageHeight - 20)
  
  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.setFont("helvetica", "normal")
  doc.text("Generated by OneLink Property Management System", 14, pageHeight - 12)
  
  // FIX: Timestamp dd/mm/yyyy
  const timestamp = new Date().toLocaleString('en-GB')
  doc.text(timestamp, 195, pageHeight - 12, { align: 'right' })

  

  doc.save(`Receipt-${rentPeriod}-${invoice.leases?.tenants?.name}-${invoice.id.slice(0,6)}.pdf`)
}