import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface StatementOptions {
  title: string
  subtitle?: string
  entityInfo?: string[]
  columns: string[]
  data: any[][]
  filename: string
}

export const generateStatementPDF = ({ title, subtitle, entityInfo, columns, data, filename }: StatementOptions) => {
  const doc = new jsPDF()

  // --- 1. HEADER & BRANDING ---
  doc.setFontSize(22)
  doc.setTextColor(22, 163, 74)
  doc.setFont("helvetica", "bold")
  doc.text("OneLink PMS", 14, 20)

  doc.setFontSize(9)
  doc.setTextColor(100)
  doc.setFont("helvetica", "normal")
  doc.text("Umuyenzi Plaza", 14, 26)
  doc.text("Kigali, Rwanda", 14, 30)

  doc.setFontSize(16)
  doc.setTextColor(0)
  doc.setFont("helvetica", "bold")
  doc.text(title.toUpperCase(), 195, 20, { align: 'right' })
  
  if (subtitle) {
    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.setFont("helvetica", "normal")
    doc.text(subtitle, 195, 26, { align: 'right' })
  }

  // --- 2. REPORT DETAILS BOX ---
  doc.setFillColor(249, 250, 251) 
  doc.setDrawColor(229, 231, 235) 
  doc.roundedRect(14, 38, 182, 24, 2, 2, 'FD')

  doc.setFontSize(10)
  doc.setTextColor(50)
  // FIX: Date Generated dd/mm/yyyy
  doc.text(`Date Generated: ${new Date().toLocaleDateString('en-GB')}`, 20, 48)

  if (entityInfo && entityInfo.length > 0) {
     let yPos = 48
     entityInfo.forEach((info) => {
        doc.text(info, 190, yPos, { align: 'right' })
        yPos += 6
     })
  }

  // --- 3. DATA TABLE ---
  autoTable(doc, {
    startY: 70,
    head: [columns],
    body: data,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], 
      textColor: 255,
      fontStyle: 'bold',
      halign: 'left'
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      textColor: 50,
      lineColor: [229, 231, 235],
      lineWidth: 0.1
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    didDrawPage: (data) => {
        const pageHeight = doc.internal.pageSize.height
        const pageWidth = doc.internal.pageSize.width
        
        doc.setDrawColor(200)
        doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15)
        
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text("Generated by OneLink Property Management System", 14, pageHeight - 10)
        
        const pageNum = "Page " + doc.getNumberOfPages()
        doc.text(pageNum, 195, pageHeight - 10, { align: 'right' })
    }
  })

  doc.save(filename)
}