import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// --- 1. SIMPLE FLAT STATEMENT (For Invoices Page) ---
interface StatementOptions {
  title: string
  subtitle: string
  entityInfo: string[]
  columns: string[]
  data: string[][]
  filename: string
}

export const generateStatementPDF = ({ 
  title, 
  subtitle, 
  entityInfo, 
  columns, 
  data, 
  filename 
}: StatementOptions) => {
  const doc = new jsPDF()
  const brandColor = [22, 163, 74] as [number, number, number]
  const headerColor = [30, 41, 59] as [number, number, number]
  const margin = 14
  const pageWidth = doc.internal.pageSize.width

  // Header
  doc.setFontSize(22); doc.setFont("helvetica", "bold"); doc.setTextColor(...brandColor)
  doc.text("OneLink PMS", margin, 20)
  
  doc.setFontSize(9); doc.setFont("helvetica", "normal"); doc.setTextColor(100)
  doc.text("Umuyenzi Plaza", margin, 26); doc.text("Kigali, Rwanda", margin, 30)

  doc.setFontSize(16); doc.setFont("helvetica", "bold"); doc.setTextColor(0)
  doc.text(title.toUpperCase(), pageWidth - margin, 20, { align: 'right' })
  
  doc.setFontSize(10); doc.setFont("helvetica", "normal"); doc.setTextColor(100)
  doc.text(subtitle, pageWidth - margin, 26, { align: 'right' })

  // Info Box
  doc.setFillColor(249, 250, 251); doc.setDrawColor(229, 231, 235)
  doc.roundedRect(margin, 38, pageWidth - (margin * 2), 24, 3, 3, 'FD')
  
  doc.setFontSize(10); doc.setTextColor(80)
  doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, margin + 6, 50)

  doc.setTextColor(0)
  let infoY = 46
  entityInfo.forEach((line) => {
    doc.text(line, pageWidth - margin - 6, infoY, { align: 'right' })
    infoY += 6
  })

  // Table
  autoTable(doc, {
    startY: 70,
    head: [columns],
    body: data,
    theme: 'grid',
    headStyles: { fillColor: headerColor, textColor: 255, fontStyle: 'bold', cellPadding: 4 },
    styles: { fontSize: 9, cellPadding: 4, textColor: 50, lineColor: [229, 231, 235], lineWidth: 0.1 },
    // @ts-ignore
    columnStyles: { [columns.length - 1]: { halign: 'right', fontStyle: 'bold' } }
  })

  // Footer
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(8); doc.setTextColor(150); doc.setFont("helvetica", "normal")
  doc.text("Generated by OneLink PMS", margin, pageHeight - 10)
  doc.save(filename)
}


// --- 2. GROUPED MONTHLY STATEMENT (For Tenant History) ---
interface GroupedStatementOptions {
  title: string
  subtitle: string
  entityInfo: string[] 
  grandTotal: string
  groups: {
    month: string
    subtotal: string
    rows: string[][]
  }[]
  filename: string
}

export const generateGroupedStatementPDF = ({ 
  title, 
  subtitle, 
  entityInfo, 
  grandTotal,
  groups, 
  filename 
}: GroupedStatementOptions) => {
  const doc = new jsPDF()
  const brandColor = [22, 163, 74] as [number, number, number]
  const headerColor = [30, 41, 59] as [number, number, number]
  const margin = 14
  const pageWidth = doc.internal.pageSize.width

  // Header
  doc.setFontSize(22); doc.setFont("helvetica", "bold"); doc.setTextColor(...brandColor)
  doc.text("OneLink PMS", margin, 20)
  
  doc.setFontSize(9); doc.setFont("helvetica", "normal"); doc.setTextColor(100)
  doc.text("Umuyenzi Plaza", margin, 26); doc.text("Kigali, Rwanda", margin, 30)

  doc.setFontSize(16); doc.setFont("helvetica", "bold"); doc.setTextColor(0)
  doc.text(title.toUpperCase(), pageWidth - margin, 20, { align: 'right' })
  
  doc.setFontSize(10); doc.setFont("helvetica", "normal"); doc.setTextColor(100)
  doc.text(subtitle, pageWidth - margin, 26, { align: 'right' })

  // Info Box
  doc.setFillColor(249, 250, 251); doc.setDrawColor(229, 231, 235)
  doc.roundedRect(margin, 38, pageWidth - (margin * 2), 24, 3, 3, 'FD')
  
  doc.setFontSize(10); doc.setTextColor(80)
  doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, margin + 6, 50)

  doc.setTextColor(0)
  let infoY = 46
  entityInfo.forEach((line) => {
    if (line.toLowerCase().includes("total")) doc.setFont("helvetica", "bold")
    else doc.setFont("helvetica", "normal")
    doc.text(line, pageWidth - margin - 6, infoY, { align: 'right' })
    infoY += 6
  })

  // Dynamic Monthly Tables
  let currentY = 70

  groups.forEach((group) => {
    if (currentY > 250) { doc.addPage(); currentY = 20; }

    // Month Header
    doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.setTextColor(0)
    doc.text(group.month, margin, currentY)

    // Subtotal
    doc.setFontSize(10); doc.setTextColor(100)
    doc.text(`Subtotal: ${group.subtotal}`, pageWidth - margin, currentY, { align: 'right' })

    currentY += 4

    // Table
    autoTable(doc, {
        startY: currentY,
        head: [['Date', 'Type', 'Unit', 'Notes', 'Amount']],
        body: group.rows,
        theme: 'grid',
        headStyles: { fillColor: headerColor, textColor: 255, fontStyle: 'bold', cellPadding: 3, fontSize: 9 },
        styles: { fontSize: 9, cellPadding: 3, textColor: 50, lineColor: [229, 231, 235], lineWidth: 0.1 },
        columnStyles: { 0: { cellWidth: 25 }, 4: { halign: 'right', fontStyle: 'bold' } },
        margin: { left: margin, right: margin }
    })
    // @ts-ignore
    currentY = doc.lastAutoTable.finalY + 12
  })

  // Grand Total Box
  if (currentY > 250) { doc.addPage(); currentY = 20; }
  
  doc.setFillColor(...brandColor)
  doc.rect(pageWidth - margin - 60, currentY, 60, 10, 'F')
  
  doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.setTextColor(255)
  doc.text("TOTAL PAID", pageWidth - margin - 55, currentY + 7)
  doc.text(grandTotal, pageWidth - margin - 2, currentY + 7, { align: 'right' })

  // Footer
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(8); doc.setTextColor(150); doc.setFont("helvetica", "normal")
  doc.text("Generated by OneLink PMS", margin, pageHeight - 10)
  doc.save(filename)
}