import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface StatementItem {
  due_date: string
  unit_number: string
  payment_date: string | null
  amount: number
  amount_paid: number
  statusLabel: string
  lateText: string
}

interface StatementSummary {
  totalBilled: number
  totalPaid: number
  balance: number
}

interface TenantStatementOptions {
  tenantName: string
  data: StatementItem[]
  summary: StatementSummary
}

export const generateTenantStatementPDF = ({ tenantName, data, summary }: TenantStatementOptions) => {
  const doc = new jsPDF()

  // --- 1. BRANDING & HEADER ---
  // Company Logo/Name
  doc.setFontSize(22)
  doc.setTextColor(22, 163, 74) // Green-600
  doc.setFont("helvetica", "bold")
  doc.text("OneLink PMS", 14, 20)

  // Sub-header / Address
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.setFont("helvetica", "normal")
  doc.text("Umuyenzi Plaza", 14, 25)
  doc.text("Kigali, Rwanda", 14, 30)

  // Report Title (Right Aligned)
  doc.setFontSize(16)
  doc.setTextColor(0)
  doc.setFont("helvetica", "bold")
  doc.text("TENANT STATEMENT", 195, 20, { align: 'right' })
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.setFont("helvetica", "normal")
  doc.text("Statement of Account", 195, 26, { align: 'right' })

  // --- 2. TENANT DETAILS BOX ---
  doc.setFillColor(249, 250, 251) // Slate-50
  doc.setDrawColor(229, 231, 235) // Slate-200
  doc.roundedRect(14, 38, 182, 24, 2, 2, 'FD')

  doc.setFontSize(10)
  doc.setTextColor(50)
  
  // Left: Date
  doc.text(`Statement Date: ${new Date().toLocaleDateString('en-GB')}`, 20, 48)
  
  // Right: Tenant Name
  doc.setFont("helvetica", "bold")
  doc.text(`Tenant: ${tenantName}`, 190, 48, { align: 'right' })
  
  // Right: Balance Context
  doc.setFont("helvetica", "normal")
  const balanceLabel = summary.balance > 0 ? "Amount Due" : "Credit Balance"
  doc.text(`${balanceLabel}: ${summary.balance.toLocaleString()} RWF`, 190, 56, { align: 'right' })

  // --- 3. DATA PREPARATION ---
  const tableRows = data.map(row => [
    new Date(row.due_date).toLocaleDateString('en-GB'),
    row.unit_number,
    row.payment_date ? new Date(row.payment_date).toLocaleDateString('en-GB') : '-',
    `${Number(row.amount).toLocaleString()}`,
    `${Number(row.amount_paid).toLocaleString()}`,
    row.statusLabel,
    row.lateText || '-'
  ])

  // --- 4. TABLE RENDER ---
  autoTable(doc, {
    startY: 70,
    head: [['Due Date', 'Unit', 'Date Paid', 'Invoice Total', 'Paid Amount', 'Status', 'Notes']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], // Slate-800
      textColor: 255,
      fontStyle: 'bold',
      halign: 'left'
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      textColor: 50,
      lineColor: [229, 231, 235],
      lineWidth: 0.1
    },
    columnStyles: {
      3: { halign: 'right', fontStyle: 'bold' }, // Invoice Total
      4: { halign: 'right', fontStyle: 'bold' }, // Paid Amount
      5: { fontStyle: 'bold' } // Status
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    // Footer on pages
    didDrawPage: (data) => {
        const pageHeight = doc.internal.pageSize.height
        const pageWidth = doc.internal.pageSize.width
        doc.setDrawColor(200)
        doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15)
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text("Generated by OneLink Property Management System", 14, pageHeight - 10)
        const pageNum = "Page " + doc.getNumberOfPages()
        doc.text(pageNum, 195, pageHeight - 10, { align: 'right' })
    }
  })

  // --- 5. SUMMARY SECTION (Bottom of Statement) ---
  // @ts-ignore
  let finalY = doc.lastAutoTable.finalY + 10
  
  // Check if we need a new page for summary
  if (finalY > doc.internal.pageSize.height - 40) {
    doc.addPage()
    finalY = 20
  }

  // Summary Box
  doc.setDrawColor(22, 163, 74) // Green border
  doc.setLineWidth(0.5)
  doc.line(120, finalY, 196, finalY) // Top line

  doc.setFontSize(10)
  doc.setTextColor(50)
  
  // Totals
  doc.text("Total Billed:", 140, finalY + 8)
  doc.text(`${summary.totalBilled.toLocaleString()} RWF`, 195, finalY + 8, { align: 'right' })

  doc.text("Total Paid:", 140, finalY + 14)
  doc.text(`${summary.totalPaid.toLocaleString()} RWF`, 195, finalY + 14, { align: 'right' })

  // Balance Line
  doc.setDrawColor(200)
  doc.line(140, finalY + 18, 195, finalY + 18)

  // Final Balance
  doc.setFontSize(12)
  doc.setFont("helvetica", "bold")
  if (summary.balance > 0) {
      doc.setTextColor(220, 38, 38) // Red for debt
      doc.text("Balance Due:", 140, finalY + 26)
  } else {
      doc.setTextColor(22, 163, 74) // Green for paid/credit
      doc.text("Balance:", 140, finalY + 26)
  }
  doc.text(`${summary.balance.toLocaleString()} RWF`, 195, finalY + 26, { align: 'right' })

  // --- 6. SAVE ---
  const safeName = tenantName.replace(/\s+/g, '_')
  doc.save(`${safeName}_Statement_${new Date().toISOString().split('T')[0]}.pdf`)
}