import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface TenantListOptions {
  tenants: any[]
  filterContext: {
    status: string
    property: string
  }
}

export const generateTenantListPDF = ({ tenants, filterContext }: TenantListOptions) => {
  const doc = new jsPDF()

  // --- 1. BRANDING & HEADER ---
  doc.setFontSize(22)
  doc.setTextColor(22, 163, 74) 
  doc.setFont("helvetica", "bold")
  doc.text("OneLink PMS", 14, 20)

  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.setFont("helvetica", "normal")
  doc.text("Property Management Solutions", 14, 25)

  doc.setFontSize(16)
  doc.setTextColor(0)
  doc.setFont("helvetica", "bold")
  doc.text("TENANT DIRECTORY", 195, 20, { align: 'right' })

  // --- 2. METADATA ---
  doc.setFillColor(249, 250, 251) 
  doc.setDrawColor(229, 231, 235) 
  doc.roundedRect(14, 32, 182, 20, 2, 2, 'FD')

  doc.setFontSize(9)
  doc.setTextColor(50)
  
  // FIX: Date Generated dd/mm/yyyy
  doc.text(`Generated: ${new Date().toLocaleString('en-GB')}`, 20, 40)
  doc.text(`Total Tenants: ${tenants.length}`, 20, 46)

  doc.text(`Status Filter: ${filterContext.status}`, 190, 40, { align: 'right' })
  doc.text(`Property: ${filterContext.property}`, 190, 46, { align: 'right' })

  // --- 3. DATA PREPARATION ---
  const tableData = tenants.map(t => {
    // @ts-ignore
    const activeLease = t.leases?.find((l: any) => l.status === 'ACTIVE')
    const location = activeLease 
      ? `${activeLease.units?.properties?.name || ''} - ${activeLease.units?.unit_number || ''}`
      : 'No Active Unit'
      
    return [
      t.name,
      t.phone,
      t.email || '-',
      t.national_id || '-',
      location,
      t.status
    ]
  })

  // --- 4. TABLE RENDER ---
  autoTable(doc, {
    startY: 60,
    head: [['Name', 'Phone', 'Email', 'National ID', 'Location', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], 
      textColor: 255,
      fontStyle: 'bold',
      halign: 'left'
    },
    styles: {
      fontSize: 8, 
      cellPadding: 3,
      textColor: 50,
      lineColor: [229, 231, 235],
      lineWidth: 0.1,
      overflow: 'ellipsize'
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 35 }, 
      4: { cellWidth: 40 }, 
      5: { fontStyle: 'bold' } 
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    didDrawPage: (data) => {
        const pageHeight = doc.internal.pageSize.height
        const pageWidth = doc.internal.pageSize.width
        
        doc.setDrawColor(200)
        doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15)
        
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text("Generated by OneLink Property Management System", 14, pageHeight - 10)
        
        const pageNum = "Page " + doc.getNumberOfPages()
        doc.text(pageNum, 195, pageHeight - 10, { align: 'right' })
    }
  })

  const fileName = `Tenant_List_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}