import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface UnitListOptions {
  propertyName: string
  units: any[]
  filterStatus: string
}

export const generateUnitListPDF = ({ propertyName, units, filterStatus }: UnitListOptions) => {
  const doc = new jsPDF()

  // --- 1. BRANDING & HEADER ---
  doc.setFontSize(22)
  doc.setTextColor(22, 163, 74) // Green-600
  doc.setFont("helvetica", "bold")
  doc.text("OneLink PMS", 14, 20)

  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.setFont("helvetica", "normal")
  doc.text("Property Inventory Report", 14, 25)

  // Report Title
  doc.setFontSize(16)
  doc.setTextColor(0)
  doc.setFont("helvetica", "bold")
  doc.text("UNIT STATUS LIST", 195, 20, { align: 'right' })

  // --- 2. PROPERTY METADATA BOX ---
  doc.setFillColor(249, 250, 251) // Slate-50
  doc.setDrawColor(229, 231, 235) // Slate-200
  doc.roundedRect(14, 32, 182, 24, 2, 2, 'FD')

  doc.setFontSize(9)
  doc.setTextColor(50)
  
  // Left: Property Info
  doc.setFont("helvetica", "bold")
  doc.text(`Property: ${propertyName}`, 20, 40)
  
  doc.setFont("helvetica", "normal")
  doc.text(`Generated: ${new Date().toLocaleString('en-GB')}`, 20, 46)
  doc.text(`Total Units: ${units.length}`, 20, 52)

  // Right: Occupancy Stats
  const occupied = units.filter(u => u.status === 'OCCUPIED').length
  const vacant = units.filter(u => u.status === 'VACANT').length
  const occupancyRate = units.length > 0 ? Math.round((occupied / units.length) * 100) : 0

  doc.text(`Occupancy Rate: ${occupancyRate}%`, 190, 40, { align: 'right' })
  doc.text(`Occupied: ${occupied} | Vacant: ${vacant}`, 190, 46, { align: 'right' })
  doc.text(`Filter Used: ${filterStatus}`, 190, 52, { align: 'right' })

  // --- 3. DATA PREPARATION ---
  const tableData = units.map(u => [
    u.unit_number,
    u.floor_number || '-',
    u.status,
    `${Number(u.rent_amount).toLocaleString()} RWF`
  ])

  // --- 4. TABLE RENDER ---
  autoTable(doc, {
    startY: 65,
    head: [['Unit Number', 'Floor', 'Status', 'Monthly Rent']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], // Slate-800
      textColor: 255,
      fontStyle: 'bold',
      halign: 'left'
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      textColor: 50,
      lineColor: [229, 231, 235],
      lineWidth: 0.1
    },
    columnStyles: {
      0: { fontStyle: 'bold' }, // Unit Number
      2: { fontStyle: 'bold' }, // Status
      3: { halign: 'right' }    // Rent
    },
    didDrawPage: (data) => {
        const pageHeight = doc.internal.pageSize.height
        
        doc.setDrawColor(200)
        doc.line(14, pageHeight - 15, doc.internal.pageSize.width - 14, pageHeight - 15)
        
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text("Generated by OneLink Property Management System", 14, pageHeight - 10)
        
        const pageNum = "Page " + doc.getNumberOfPages()
        doc.text(pageNum, 195, pageHeight - 10, { align: 'right' })
    }
  })

  // --- 5. SAVE ---
  const safeName = propertyName.replace(/\s+/g, '_')
  doc.save(`${safeName}_Units_${new Date().toISOString().split('T')[0]}.pdf`)
}